name: Publish ZENV Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ceoseshell
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build de l’image ZENV
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VERSION=${{ github.sha }} \
            -t ceoseshell/zenv:latest \
            -t ceoseshell/zenv:${{ github.run_number }} .

      # 4. Push vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ceoseshell/zenv:latest
          docker push ceoseshell/zenv:${{ github.run_number }}

      # 5. Publier le README comme description Docker Hub
      - name: Publish README to Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ceoseshell
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ceoseshell/zenv
          readme-filepath: ./README.md
